server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: strict

spring:
  profiles:
    active: dev


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresSQLDialect

  spring:
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML
      encoding: UTF-8

  app:
    security:
      remember-me:
        key: taolarememberkey
        validity: 604800

  email:
    verification:
      expiration: 86400
      password-reset:
        expiration: 3600
